### ISSUE TITLE
date_created field isn't updated

### ISSUE THREAD

**Issue by tr0ldmand** [tr0ldmand/com_bloodbowl25#1]
field date_created in table bb_matches isn't updated at first match reporting, causing the status of players to not be updated, ie. injuries/mng is reported wrong.

**Comment by tr0ldmand** [comment]
Affected matches can be found by running:
SELECT \* FROM `##_bb_matches` WHERE `date_created` IS NULL AND `date_played` IS NOT NULL

**Comment by Cosworth32** [comment]
One potential fix would be to use timestamp as type instead of datetime and initialise it with current time:
http://dev.mysql.com/doc/refman/5.1/en/timestamp-initialization.html

The bb_matches table would have to be created with:
`date_created` timestamp DEFAULT CURRENT_TIMESTAMP,

**Comment by Cosworth32** [comment]
This mysql workaround ensures date_created is set when an update occurs:

CREATE TRIGGER `date_created` BEFORE UPDATE ON `gd8h_bb_matches`
 FOR EACH ROW BEGIN
  IF OLD.date_created IS NULL THEN
    SET NEW.date_created = NEW.date_modified;  
  END IF;
END

Works like a charm. date_modified doesn't suffer from update problems as it is always set unconditionally when a match is updated.

**Comment by Cosworth32** [comment]
So the commit was merged but was the SQL trigger implemented?

**Comment by tr0ldmand** [comment]
Joomla won't allow the trigger in the install script. It is not granted that Joomla is run on a MySQL database supporting triggers.
TRIGGER was installed on production database nontheless.

**Comment by Cosworth32** [comment]
Should be closeable now.db trigger can be removed or left in place it shouldn't make any difference
